### ISSUE TITLE
Fulfillments does not implement IGetsResourceUrlResponses

### ISSUE THREAD

**Issue by mkercheval-tva** [nla-brandonjames/ShipStation4Net#38]
Fulfillments does not implement IGetsResourceUrlResponses 

Webhooks can return https://ssapi.shipstation.com/fulfillment as the url parameter. Shipment and Orders both already support IGetsResourceUrlResponses seems only Fulfillments is missing

**Comment by mv-vlad-kurdesov** [comment]
should be included in 1.0.6 version
