### ISSUE TITLE
Question: Suggested improvements

### ISSUE THREAD

**Issue by vlad-kurdesov** [nla-brandonjames/ShipStation4Net#4]
Hey,
wanted to ask your opinion about couple things:
1) what do you think about adding RetryPolicy to the client? e.g. current handling would be 'No Retry', and then we could add 'RetryOnApiLimit' or something which would wait required time until time limit is reset & try 3-4 times to get same api call thru. This would help to make methods like GetAllPages more stable, because these methods need to make multiple api calls in a sequence. This also would help to prevent ApiLimitExceeded exceptions in tests that currently failing on master branch. I researched it a little bit, and there is Microsoft package TransientFaultHandling.Core which defines some base classes for RetyPolicies, but I'm not sure if this package supports 2.0 .net standard. + in our case, retry policy will be very specific to ApiLimitException, so I think that only 'No Retry' policy could be reused in this case...
2) what do you think about making all properties nullable for objects we're sending & receiving from ShipStation? I looked thru documentation of ShipStation and they don't really tell what is optional and what is always present in response. One of current issues is that shipDate on order is nullable in some cases, and it's required in model, so deserialization breaks. Another approach is to see where it breaks and make only specific fields nullable, and hope that ShipStation doesn't change flow or specification.

If you are good with these changes, I will apply them & send pull request. I will start looking at it today/tomorrow.
And last, but not least, question.. After these changes are done, could you please compile and publish new nuget package? I'm trying to help my team with one improvement project, and part of the change we're trying to make is to remove internal sdk we built in past to communicate with ShipStation, and replace it with package that available on nuget. We tried to use one of nuget packages in past, but that package was missing pagination and good error handling, so we went with our own 'bicycle' which we're trying to deprecate. We have clients on production which use ShipStation heavily in multiple countries, so I will possibly look at other model objects and add any if missing.

**Comment by nla-brandonjames** [comment]
I approve of those developments. I haven't had time to test this client lately for POST/PUT requests, but if you were to contribute in that way, I think the features you suggested would come in handy. I appreciate the interest.

I will re-publish the NuGet package after accepting that pull request. Sorry about any inconvenience. I've been helping my business by moving hardware from one side of our city to the other one the past two weeks so my attention has been distracted from actual software development lately. We got all settled yesterday so I should return back to situation normal.

Thanks,
Brandon

**Comment by nla-brandonjames** [comment]
Accepted PR #5
